version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: chicken
      RABBITMQ_DEFAULT_PASS: chicken
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq # Bind mount
      # - rabbitmqdata:/data # Named volume

volumes:
  rabbitmq: # Named volume
