version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db # Bind mount
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data # Bind mount
    command: redis-server --appendonly yes
